name: "CI/CD Pipeline"

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        if: false
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup QEMU
        if: false
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        if: false
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        if: false
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/app
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/cicd-test:latest

  test:

    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Setup Trivy
        if: false
        uses: aquasecurity/trivy-action@0.31.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/cicd-test:latest
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
        
      - name: Run tests
        run: |
          echo "Running tests..."

  deploy:

    runs-on: ubuntu-latest
    needs: test
    steps:

      - name: Setup SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 400 private_key
          ssh -i private_key.pem ubuntu@${{ secrets.SERVER_IP }}
          docker pull ${{ secrets.DOCKER_USERNAME }}/cicd-test:latest
          docker run -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/cicd-test:latest