name: "CI/CD Pipeline"

on:
	workflow_dispatch:

jobs:
	build:
		runs-on: ubuntu-latest
		steps:
			- name: Checkout code
				uses: actions/checkout@v4

			- name: Login to DockerHub
				uses: docker/login-action@v3
				with:
					username: ${{ secrets.DOCKER_USERNAME }}
					password: ${{ secrets.DOCKER_PASSWORD }}

			- name: Setup QEMU
				uses: docker/setup-qemu-action@v3

			- name: Setup Buildx
				uses: docker/setup-buildx-action@v3

			- name: Build and push Docker image
				uses: docker/build-push-action@v6
				with:
					context: "{{ github.workspace }}/app"
					file: Dockerfile
					push: true
					platforms: linux/amd64
					tags: ${{ secrets.DOCKER_USERNAME }}/cicd-test:latest